SELECT * FROM (
SELECT  City, LENGTH(City)
FROM Station
WHERE LENGTH(City) = (SELECT MIN(LENGTH(City)) FROM Station) 
ORDER BY City)
WHERE ROWNUM = 1;
SELECT * FROM (
SELECT  City, LENGTH(City)
FROM Station
WHERE LENGTH(City) = (SELECT MAX(LENGTH(City)) FROM Station) 
ORDER BY City)
WHERE ROWNUM = 1;